FROM php:8.4-fpm

# Dépendances système
RUN apt-get update && apt-get install -y \
    git curl nginx supervisor \
    libpng-dev libonig-dev libxml2-dev \
    libpq-dev libzip-dev zip unzip \
    && docker-php-ext-install pdo pdo_pgsql mbstring exif pcntl bcmath gd zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www

COPY . .

# Install dependencies
RUN composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

# Permissions
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache \
    && chmod -R 775 /var/www/storage /var/www/bootstrap/cache

# Nginx config
COPY docker/nginx/render.conf /etc/nginx/sites-available/default

# Supervisord config
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

EXPOSE 10000

COPY docker/start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/start.sh"]
